In [1]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

import plotly
import plotly.graph_objs as go
import plotly.express as px
from plotly.subplots import make_subplots

In [2]:
number_of_pages = 100
#number_of_ads = number_of_pages * per_page

job_title = ["'Data Analyst' or 'data scientist'"]
for job in job_title:
    data=[]
    for i in range(number_of_pages):
        url = 'https://api.hh.ru/vacancies'
        par = {'text': job, 'area':'113','per_page':'10', 'page':i}
        r = requests.get(url, params=par)
        e=r.json()
        data.append(e)
        vacancy_details = data[0]['items'][0].keys()
        df = pd.DataFrame(columns= list(vacancy_details))
        ind = 0
        for i in range(len(data)):
            for j in range(len(data[i]['items'])):
                df.loc[ind] = data[i]['items'][j]
                ind+=1
    csv_name = job+".csv"
    df.to_csv(csv_name)

In [3]:
data = df.copy()

In [4]:
data.shape

(1000, 31)

In [5]:
data.head()

,id,premium,name,department,has_test,response_letter_required,area,salary,type,address,...,employer,snippet,contacts,schedule,working_days,working_time_intervals,working_time_modes,accept_temporary,professional_roles,accept_incomplete_resumes
0,77613664,False,Data Scientist,None,True,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 150000, 'to': 200000, 'currency': 'RU...","{'id': 'open', 'name': 'Открытая'}",None,...,"{'id': '2887273', 'name': 'Retail Rocket', 'ur...",{'requirement': 'Опыт работы в области рекомен...,None,None,[],[],[],False,"[{'id': '165', 'name': 'Дата-сайентист'}]",False
1,76913797,False,Data-Scientist / Дата-сайентист,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,"{'id': 'open', 'name': 'Открытая'}",None,...,"{'id': '5846248', 'name': 'Employcity', 'url':...",{'requirement': 'Уверенное владение Python. Оп...,None,None,[],[],[],False,"[{'id': '165', 'name': 'Дата-сайентист'}]",False
2,78045027,False,Аналитик данных (Data Scientist),None,False,False,"{'id': '88', 'name': 'Казань', 'url': 'https:/...",None,"{'id': 'open', 'name': 'Открытая'}","{'city': 'Казань', 'street': 'улица Карла Марк...",...,"{'id': '1555821', 'name': 'DLS', 'url': 'https...",{'requirement': 'Уверенные знания мат. статист...,None,None,[],[],[],False,"[{'id': '165', 'name': 'Дата-сайентист'}]",False
3,78014671,False,Data Scientist,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 250000, 'to': 300000, 'currency': 'RU...","{'id': 'open', 'name': 'Открытая'}",None,...,"{'id': '4811161', 'name': 'Patron.', 'url': 'h...",{'requirement': 'Хорошую математическую и стат...,None,None,[],[],[],False,"[{'id': '10', 'name': 'Аналитик'}]",False
4,78043382,False,Senior Data Scientist,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,"{'id': 'open', 'name': 'Открытая'}","{'city': 'Москва', 'street': 'улица Раевского'...",...,"{'id': '2155808', 'name': 'ГПМ Партнер', 'url'...",{'requirement': 'Отличное знание Python. Знани...,None,None,[],[],[],False,"[{'id': '165', 'name': 'Дата-сайентист'}]",False

In [6]:
data = data[['area', 'salary']]

In [7]:
data = data[data['address'].isna() == False].reset_index(drop=True)

KeyError: 'address'

In [ ]:
data.shape

In [ ]:
for i in range(len(data)):
    data['area'][i] = data['area'][i]['name']

In [ ]:
for i in range(len(data)):
    if data['area'][i] != 'Москва' and data['area'][i] != 'Санкт-Петербург':
        data['area'][i] = 'Другой'

In [ ]:
fig = go.Figure()
fig.add_trace(go.Pie(values=data.groupby('area')['area'].count(), labels=data.groupby('area')['area'].count().index, sort = False))
fig.show()

In [ ]:
data = data[data['area'] == 'Санкт-Петербург'].reset_index(drop=True)
data